// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsqjvrqzvotpzwfixjzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcWp2cnF6dm90cHp3Zml4anpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODM2ODcsImV4cCI6MjA1ODU1OTY4N30.0uCgWIW6WGMw8Y1P0kMmcpkkzZbvgo4AVBX4Zfi7TTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);